// src/domains/orders/schemas/counter.schema.ts

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

@Schema({ 
  timestamps: true, 
  collection: 'counters' // Explicitly naming the collection 'counters'
})
export class Counter {
  @Prop({ required: true, unique: true }) // Added unique: true for extra safety
  tenantId!: string; 

  @Prop({ default: 0 })
  seq!: number; 

  @Prop({ default: Date.now })
  lastResetDate!: Date; 
}

/**
 * Mongoose Document type for use in the Model injection
 * (e.g., Model<CounterDocument>)
 */
export type CounterDocument = Counter & Document;

/**
 * The Schema generated by NestJS/Mongoose
 */
export const CounterSchema = SchemaFactory.createForClass(Counter);